### ISSUE TITLE
In the Service Bus lab we couldn't see anywhere where it gets you to create the visits-confirmations   queue

### ISSUE THREAD

**Issue by jolguk** [Azure-Samples/java-microservices-asa-e-lab#7]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
In the Service Bus lab we couldn't see anywhere where it gets you to create the visits-confirmations   queue so we ended up just creating one manually
### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by fmustaf** [comment]
Step added to create the visits-confirmations queue in 06_lab_messaging/0601.md

**Comment by fmustaf** [comment]
Therefore closing the issue as addressed
